Repository jenkinsci/pull-request-monitoring-plugin, pull requests merged in 2021-06, with the labels that each got.

#90 fix ugly presentation of json configuration, introduce json tree view
  etc/images/add-portlet.png
  etc/images/missing-portlet.png
  etc/images/settings.png
  src/main/resources/alerts/warning.properties
  src/main/resources/modals/config.jelly
  src/main/webapp/css/jsontree.css
  src/main/webapp/js/jsontree.js
  src/main/webapp/js/pull-request-monitoring.js
Labels: bug

#89 fix StackOverflowException for MonitoringDefaultActionFactory if Moni…
  pom.xml
  src/main/java/io/jenkins/plugins/monitoring/Monitor.java
  src/main/java/io/jenkins/plugins/monitoring/MonitoringCustomAction.java
  src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultAction.java
  src/main/java/io/jenkins/plugins/monitoring/MonitoringDefaultActionFactory.java
  src/test/java/io/jenkins/plugins/monitoring/MonitorTest.java
Labels: bug

#92 remove dramatic jenkins error svg from project action, if no pull req…
  src/main/resources/io/jenkins/plugins/monitoring/MonitoringMultibranchProjectAction/index.jelly
Labels: internal

#93 fix npe for unsupported projects
  src/main/java/io/jenkins/plugins/monitoring/util/PullRequestFinder.java
Labels: bug

#95 add pr auto assignment
  .github/auto_assign.yml
  .github/workflows/assign-pr.yml
Labels: github_actions

#103 Update dependencies of UI libraries to latest versions
  pom.xml
Labels: dependencies

#112 Revert "Bump j2html from 1.4.0 to 1.5.0"
  pom.xml
Labels: bug
